executor: slurm
default-resources:
  slurm_walltime: 3600
  slurm_partition: workstations
  ntasks: 1
  cpus_per_task: 1
  runtime: 60
  nodes: 4
set_resources:
  slurm_extra: "'latency_wait=600'"

jobs: 4
use-conda: True
conda-frontend: conda
